name: KAJ Site
description: Blogging about stuffs
meta_description: "KAJ Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "http://KyungAhblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "KyungAh Jang"

# Disqus config
disqus-shortname: ""
